nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:5173'] # Vue dev server origin
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['Content-Type']
    max_age: 3600
    allow_credentials: true
  paths:
    '^/api/':
      allow_origin: ['http://localhost:5173']
      allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
      allow_headers: ['Content-Type', 'Authorization']
      max_age: 3600